chore: comments for error + persistance

diff --git a/start-k8s-shiny b/start-k8s-shiny
--- a/start-k8s-shiny
+++ b/start-k8s-shiny
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
+# example use case: ./start-k8s-shiny production
+
 # Set the environment variable to the first command-line argument or default to 'staging'
 ENV=${1:-staging}
-
+if [[ "$ENV" != "staging" && "$ENV" != "production" ]]; then
+    echo "Error: env must be either 'staging' or 'production'"
+    exit 1
+fi
 # Make the script itself executable
 chmod +x "$0"
 
